### ISSUE TITLE
patch file format documentation

### ISSUE THREAD

**Issue by ZpmFred** [sisong/HDiffPatch#102]
Is it possible to add a documentation of the binary format of the patch file used by hpatchz ?

**Comment by sisong** [comment]
Documentation  is not easy to write ，because need use my little  English;      
Do you want to implement a decoder of your own?       
   
You can read source code :  patch() in patch.c file，is the simplest reader version;   
and the writer is serialize_diff() in diff.cpp;     
Other stream or compressed reader/writer version are too complicated.

**Comment by sisong** [comment]
>> “stream patch is so awesomely fast”       
what is "stream patch" comparing with？cause you think it is “awesomely fast”.     
I don't think there is any magic in the format;
