### ISSUE TITLE
patch using a diffz stream

### ISSUE THREAD

**Issue by BrianPugh** [sisong/HDiffPatch#169]
I'm trying to patch a binary file (using a zlib compressed patch) on an embedded device give the following:
    * Input Old data is local.
    * Output patched data will be local.
    * Diff patch data is being streamed over a wireless connection.

Because of this, I do not have random access to the diff data. 

I was wondering if the following are possible:
    * Apply a diff without any random access to the diff data. Random access on old data is fine.
    * No caching on diff reads

Thanks!

**Comment by BrianPugh** [comment]
It looks like there are 3 independently compressed sections:
1. CTRL
2. CODE
3. NEWDATA
Are these accessed randomly? Or would it be possible to interleave them as they would be accessed and compress the interleaved data?

**Comment by sisong** [comment]
Your opinion is accurate; in fact, the data is divided into max 4 parts, the data is separated because for smaller compression, but this is not necessary;
You can adjust the serialization output of the diff function(serialize_diff or stream_serialize), output one compressed data stream in the original order of these data. but custom the new streaming patch code may be is a heavy workload;
Another simple option is to maintain 4 thread downloads while patching;  Or, after the download is complete, patching start;

**Comment by BrianPugh** [comment]
Thanks sisong! I'll investigate it a little further. Right now the simplest option for me is to download the complete patch and then apply it, but I'll have to solve some storage space issues. I'm going to leave this issue open for a little longer in case I have some more questions. Thanks!

**Comment by sisong** [comment]
Another idea: patching after download, use the (fast) compressed stream when outputting the new version; the second step is to delete the old version and the patch file; the third step is to uncompress out the new version;   (ps:can use lz4 for fast compress&uncompress)
