### ISSUE TITLE
对于差分文件中的压缩数据部分处理

### ISSUE THREAD

**Issue by Pippinrao** [sisong/HDiffPatch#318]
安卓的imgdiff，差分时搜索压缩数据（gzip格式）自动解压后分块再进行差分，对于普通数据直接使用bsdiff差分，Hdiff是否有或者是否可以添加类似的能力？

**Comment by sisong** [comment]
可以看看我另外的解决方案： [ApkDiffPatch](https://github.com/sisong/ApkDiffPatch) 和 [sfpatcher](https://github.com/sisong/sfpatcher)   
   
My solution 1: ApkDiffPatch; MIT license; C++; only for own apk; (can't be used by Android app store, because it requires re-signing apks before diff);   
My solution 2: sfpatcher; Business license; C++; is designed for Android app store; patch speed up by a factor of xx than archive-patcher & run with O(1) memory & not need temp files & support large game apk & support android4.1--android13.

**Comment by sisong** [comment]
HDiffPatch以添加类似的能力， 
上面两个方案都是在HDiffPatch方案之上添加的针对apk(zip)格式的特殊处理,来减少补丁大小。     
如果只是“gzip格式” ， 那 sfpatcher方案很容易就能添加支持，并且不需要更新patch端。

**Comment by Pippinrao** [comment]
感谢大佬回复
抱歉我没有描述清楚，[ApkDiffPatch](https://github.com/sisong/ApkDiffPatch) 和 [sfpatcher](https://github.com/sisong/sfpatcher)我看过，这两个方案是针对压缩文件的差分和还原，现在遇到的是固件升级（比如安卓系统升级），固件中可能包含若干个文件系统镜像（ext4格式，hash固化在内核安全启动时校验）。针对镜像文件的差分还原可能由于分块、文件系统中可能存在一些压缩数据导致差分率较差，参考[Android OTA差分](https://source.android.com/docs/core/ota/reduce_size)。

**Comment by sisong** [comment]
bsdiff能用，那hdiffpatch就肯定能用。     
重新理一下需求，你是想用hdiffpatch来解决什么问题？ 最想要更快的diff速度？ 或更小的补丁？或更快的patch速度？或内存占用更小的patch？

**Comment by Pippinrao** [comment]
需求你是对大文件更快的diff速度（bsdiff慢的离谱）和还原时更小的内存占用

**Comment by Pippinrao** [comment]
考虑了一下，*文件中的压缩部分*识别不应该在算法中实现，可能需要在上层识别分块再由算法差分比较合适

**Comment by sisong** [comment]
是的；      
简单替换bsdiff的方案比较容易实现，当前hdiffpatch已经有一个和bsdiff兼容的实现(见bsdiff_wrapper目录)。 （如果是修改版的bsdiff，那需要相对应的同样修改）

**Comment by sisong** [comment]
sfpatcher也许就是个兼容实现的上层，我把它抽象成了处理压缩流和非压缩流的混合的通用框架，并且已经同时支持了zip\apk\tar\gzip文件格式（这些格式的支持是用插件的方式提供的）。       
也许只需要一个新的理解安卓img格式的插件就能处理了。 并且很可能不需要修改任何patch端代码，提供O(1)的内存占用的patch。

**Comment by Pippinrao** [comment]
我再研究一下，谢谢回复
