### ISSUE TITLE
Please explain what means partially compatible with the vcdiff

### ISSUE THREAD

**Issue by JuniorJPDJ** [sisong/HDiffPatch#369]
Hey,
Can you please tell me more about what's partial in the compatibility between hdiffpatch and vcdiff?
It would be nice if you could also write it in readme for others ;D
Readme states this: partially compatible with the [open-vcdiff](https://github.com/google/open-vcdiff) and [xdelta3](https://github.com/jmacd/xdelta) patch file format [VCDIFF(RFC 3284)](https://www.rfc-editor.org/rfc/rfc3284).

**Comment by sisong** [comment]
run $hdiffz or $hpatchz, can see some info about VCDIFF.   
1. $hdiffz -VCD can created VCDIFF format diffFile, but diffFile used one source window size == oldFile size;     
if this diffFile patch by open-vcdiff or xdelta3, will used larger memory (all oldFile's data will be loaded in memory).
2. $hpatchz unspport some diffFile, it's created by $xdelta3 -S djw or $xdelta3 -S fgk 

( ref #316 )

**Comment by jpruciak** [comment]
so hdiffz creates fully compatible VCDIFF, but hpatchz can only apply patches created by hdiffz?

**Comment by sisong** [comment]
I'm sorry I didn't make the situation clear.   
about `partially compatible`：   
* `$hdiffz -VCD ...` created diffFile, uncompressed, compatible with VCDIFF format.   
 `$hpatchz` & `$open-vcdiff` & `$xdelta3` all can apply this diffFile;   
 `$hpatchz` requires O(1) memory when patching;
but `$open-vcdiff` & `$xdelta3` maybe requires O(oldFileSize) memory when patching. (because the diffFile used the sourceWindowSize == oldFileSize )   
* `$hdiffz -VCD-compressLevel[-dictSize] ...` created diffFile, compressed by `7zXZ`, compatible `$xdelta3 -S lzma`.   
 `$hpatchz` & `$xdelta3` can apply it;   
 `$hpatchz` requires O(3\*dictSize) memory when patching;   
 but `$xdelta3` maybe requires O(oldFileSize+3\*dictSize) memory when patching.   
* `$hpatchz` support all diffFile created by `$open-vcdiff` (includes various parameter combinations and private formats), requires O(sourceWindowSize+targetWindowSize) memory when patching;    
* `$hpatchz` support the diffFile created by `$xdelta3 -S`, requires O(sourceWindowSize+targetWindowSize) memory when patching;    
* `$hpatchz` support the diffFile created by `$xdelta3 -S lzma`, requires O(sourceWindowSize+targetWindowSize+3\*dictSize) memory when patching;    
* `$hpatchz` unsupport the diffFile created by `$xdelta3 -S djw` or `$xdelta3 -S fgk`. (hpatchz not included djw&fgk decompressor)

**Comment by sisong** [comment]
now HDiffPatch v5.0.0   
fully compatible with VCDIFF format window constraints when diff by `$hdiffz -VCD[...] -w[-oldWinSize-segSize-newWinSize]`
